from .menu import get_sub_menu_keyboard, get_invite_menu_keyboard, get_get_menu_keyboard, get_manager_canced_keyboard
from .sponsors import get_sponsors_canced_keyboard, get_sponsors_delete_keyboard, get_sponsors_keyboard
from .mailing import get_mailing_menu_keyboard, get_send_mailing_menu
from .admin import get_admin_canced_setting_keyboard, get_admin_set_menu_keyboard, get_admin_setting_menu_keyboard
from .ref import get_delete_ref_keyboard, ref_return_keyboard, get_ref_setting_menu_keyboard